services:
  backend:
    build: ./backend
    ports:
      - "3000:3000"
    volumes:
      - ./backend:/app
    depends_on:
      - db
    environment:
      - NODE_ENV=development
      - MONGODB_URI=mongodb://db:27017/kittydelivery

  frontend:
    build: ./frontend
    ports:
      - "8081:8081"
    volumes:
      - ./frontend:/app
    depends_on:
      - backend
    environment:
      - NODE_ENV=development
      - REACT_APP_API_URL=http://localhost:3000

  db:
    image: mongo
    ports:
      - "27017:27017"
    volumes:
      - mongodata:/data/db

volumes:
  mongodata: